'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { StatCard } from '@/components/StatCard';
import { AdminNav } from '@/components/AdminNav';
import { Banknote, CarFront, ReceiptText, Settings2, ArrowRight } from 'lucide-react';
export default function AdminPage(){const [s,setS]=useState({open:0,entries:0,revenue:0,ticketAverage:0});useEffect(()=>{fetch('/api/dashboard').then(r=>r.json()).then(d=>{if(!d.error)setS(d)})},[]);return <AppShell title="Gestão"><AdminNav/><div className="mb-6"><p className="text-sm font-semibold text-brand-700">VISÃO GERAL</p><h1 className="mt-1 text-3xl font-black">Dashboard</h1><p className="mt-2 text-slate-500">Indicadores essenciais de hoje.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Faturamento do dia" value={`R$ ${s.revenue.toFixed(2).replace('.',',')}`}/><StatCard label="Veículos no pátio" value={String(s.open)}/><StatCard label="Entradas hoje" value={String(s.entries)}/><StatCard label="Ticket médio" value={`R$ ${s.ticketAverage.toFixed(2).replace('.',',')}`}/></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Card icon={<ReceiptText/>} title="Movimentações" text="Histórico de entradas, saídas e pagamentos."/><Link href="/admin/tarifas"><Card icon={<Settings2/>} title="Tarifas" text="Crie tabelas, frações, tolerância e teto diário." link/></Link><Card icon={<CarFront/>} title="Clientes e veículos" text="Base recorrente preparada para evolução do produto."/></div><div className="mt-6 rounded-[2rem] border border-brand-100 bg-brand-50 p-6"><div className="flex gap-4"><span className="rounded-2xl bg-white p-3 text-brand-600"><Banknote/></span><div><h2 className="font-black">Versão 1.0.4</h2><p className="mt-1 text-sm text-slate-600">MVP comercial: operação, portal do cliente, gestão, serviços, equipe, caixa e auditoria.</p></div></div></div></AppShell>}
function Card({icon,title,text,link}:{icon:React.ReactNode;title:string;text:string;link?:boolean}){return <div className="h-full rounded-3xl bg-white p-6 shadow-sm"><span className="text-brand-600">{icon}</span><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-2 text-sm text-slate-500">{text}</p>{link&&<ArrowRight className="mt-4 text-brand-600" size={18}/>}</div>}
